vowel challenge
SeR4h/andelaweek2challenges2 pull request #3
Opened 2019-11-27 11:08 UTC by SeR4h

2019-11-27 16:08 UTC, dennisja requested changes

2019-11-27 16:08 UTC, dennisja commented on vowel.js
> +    characterCounter[paragraph.charAt(i)] =characterCounter[paragraph.charAt(i)] +1
Use the shorthand notation i.e
```js
// instead of 
x = x + 1

// do 
x += 1
```

2019-11-27 16:08 UTC, dennisja commented on vowel.js
> +    else if(characterCounter[(paragraph.charAt(i))] == 1){
Follow the indentation in the steps provided

2019-11-27 16:08 UTC, dennisja commented on vowel.js
> +function countVowels(paragraph){
Cater for the spaces?

2019-11-27 16:08 UTC, dennisja commented on vowel.js
> +    console.log(myArray)
return myArray instead of logging it

2019-11-27 16:08 UTC, dennisja commented on vowel.js
> +    newVowel= Array.from(set1).join('')
declare newVowel before use

2019-12-04 16:40 UTC, SeR4h commented
@billkabanga could you please review my code. "#final vowel modification"

2019-12-09 10:43 UTC, billkabanga commented on vowel.js
> +    countVowels(finalstring)
Please add a new line at the end of the file

2019-12-09 10:44 UTC, billkabanga commented on vowel.js
> +      console.log(characterCounter)
I suppose you need this `console.log` for debugging purposes, you should remove it when you are done using it.

2019-12-09 10:47 UTC, billkabanga commented on vowel.js
> + counter =counter+ 1
There should always be space around the operator

2019-12-16 13:05 UTC, merged